Update release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -14,6 +14,8 @@ permissions:
 
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  GITHUB_BOT_NAME: github-actions[bot]
+  GITHUB_BOT_EMAIL: github-actions[bot]@users.noreply.github.com
   PACKAGE_JSON_PATH: VContainerAnalyzer.Unity/Assets/Plugins/VContainerAnalyzer/package.json
 
 concurrency:
@@ -58,60 +60,33 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Update package.json
-        shell: pwsh
         run: |
-          $jsonContent = Get-Content -Path $env:PACKAGE_JSON_PATH | ConvertFrom-Json
-          $jsonContent.version = $env:VERSION
-          $jsonContent | ConvertTo-Json | Set-Content -Path $env:PACKAGE_JSON_PATH
-      - name: Confirm package.json diff
-        id: package-json
-        run: |
-          git add "${PACKAGE_JSON_PATH}"
-          result=0
-          git diff --cached --exit-code --quiet || result=$?
-          if [ "${result}" -eq 0 ]; then
-            echo "diff=false" >> "${GITHUB_OUTPUT}"
-          elif [ "${result}" -eq 1 ]; then
-            echo "diff=true" >> "${GITHUB_OUTPUT}"
-          else
-            echo "exit code of diff is unknown: ${result}"
-            exit 1
-          fi
+          json_content=$(cat "${PACKAGE_JSON_PATH}")
+          updated_json=$(echo "${json_content}" | jq --arg version "${VERSION}" '.version = $version')
+          echo "${updated_json}" | jq '.' > "${PACKAGE_JSON_PATH}"
       - name: Commit package.json
-        if: ${{ steps.package-json.outputs.diff == 'true' }}
-        run: |
-          git config user.email github-actions[bot]@users.noreply.github.com
-          git config user.name github-actions[bot]
-          git switch -C "${SOURCE_BRANCH}"
-          git commit -m "Update package.json"
-          git push -u origin "${SOURCE_BRANCH}"
+        uses: EndBug/add-and-commit@v9
+        id: commit-package-json
+        with:
+          author_name: ${{ env.GITHUB_BOT_NAME }}
+          author_email: ${{ env.GITHUB_BOT_EMAIL }}
+          message: "Update package.json"
+          add: ${{ env.PACKAGE_JSON_PATH }}
+          new_branch: ${{ env.SOURCE_BRANCH }}
       - name: Update README.md
         run: |
           cp -f .github/DRAFT_README.md README.md
-      - name: Confirm README.md diff
-        id: readme
-        run: |
-          git add README.md
-          result=0
-          git diff --cached --exit-code --quiet || result=$?
-          if [ "${result}" -eq 0 ]; then
-            echo "diff=false" >> "${GITHUB_OUTPUT}"
-          elif [ "${result}" -eq 1 ]; then
-            echo "diff=true" >> "${GITHUB_OUTPUT}"
-          else
-            echo "exit code of diff is unknown: ${result}"
-            exit 1
-          fi
       - name: Commit README.md
-        if: ${{ steps.readme.outputs.diff == 'true' }}
-        run: |
-          git config user.email github-actions[bot]@users.noreply.github.com
-          git config user.name github-actions[bot]
-          git switch -C "${SOURCE_BRANCH}"
-          git commit -m "Update README.md"
-          git push -u origin "${SOURCE_BRANCH}"
+        uses: EndBug/add-and-commit@v9
+        id: commit-readme
+        with:
+          author_name: ${{ env.GITHUB_BOT_NAME }}
+          author_email: ${{ env.GITHUB_BOT_EMAIL }}
+          message: "Update README.md"
+          add: "README.md"
+          new_branch: ${{ env.SOURCE_BRANCH }}
       - name: Create pull request and merge
-        if: ${{ steps.package-json.outputs.diff == 'true' || steps.readme.outputs.diff == 'true' }}
+        if: ${{ steps.commit-package-json.outputs.committed == 'true' || steps.commit-readme.outputs.committed == 'true'}}
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
@@ -127,31 +102,42 @@ jobs:
     env:
       VERSION: ${{ needs.draft.outputs.tag_name }}
     steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: main
+      - name: Confirm version in package.json
+        run: |
+          package_version=$(jq -r '.version' "${PACKAGE_JSON}")
+
+          if [[ "${package_version}" != "${VERSION}" ]]; then
+            echo "::error::version in package.json (${package_version}) does not match the release draft tag (${VERSION})"
+            exit 1
+          fi
       - uses: release-drafter/release-drafter@v6
         id: release-drafter
         with:
           publish: true
           commitish: main
-      - name: Create semver outputs
-        uses: actions/github-script@v7
-        id: semver
-        with:
-          script: |
-            const matched = "${{ env.VERSION }}".match(/(((\d+)\.\d+).\d+)/)
-            core.setOutput('major', matched[3])
-            core.setOutput('minor', matched[2])
-            core.setOutput('patch', matched[1])
+      - name: Get semver
+        id: get-semver
+        run: |
+          read -r major minor patch <<< "$(echo "${VERSION}" | grep -oE '^([0-9]+)\.([0-9]+)\.([0-9]+)' | awk -F '.' '{print $1 " " $2 " " $3}')"
+          {
+            echo "major=${major}"
+            echo "minor=${major}.${minor}"
+            echo "patch=${major}.${minor}.${patch}"
+          } >> "${GITHUB_OUTPUT}"
       - uses: actions/checkout@v4
         with:
           ref: ${{ env.VERSION }}
       - name: Update major tag
-        if: steps.semver.outputs.major != '0'
+        if: steps.get-semver.outputs.major != '0'
         run: |
-          git push -f origin "refs/tags/${VERSION}:refs/tags/${{ steps.semver.outputs.major }}"
+          git push -f origin "refs/tags/${VERSION}:refs/tags/${{ steps.get-semver.outputs.major }}"
       - name: Update minor tag
-        if: steps.semver.outputs.minor != '0.0'
+        if: steps.get-semver.outputs.minor != '0.0'
         run: |
-          git push -f origin "refs/tags/${VERSION}:refs/tags/${{ steps.semver.outputs.minor }}"
+          git push -f origin "refs/tags/${VERSION}:refs/tags/${{ steps.get-semver.outputs.minor }}"
       - name: Execute dotnet pack
         run: |
           dotnet pack ./VContainerAnalyzer/VContainerAnalyzer.csproj \
